# Generated by Django 4.2.23 on 2025-08-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('code', models.TextField(help_text='Ключ', primary_key=True, serialize=False)),
            ],
        ),
    ]
