# Generated by Django 4.2.23 on 2025-08-30 21:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passcode', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('banned', models.BooleanField(default=False)),
                ('passcodes', models.ManyToManyField(blank=True, to='passcode.passcode')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('code', models.CharField(help_text='Код доски (например, b)', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Короткое описание доски, которое пользователи видят в списке рядом с ней')),
                ('detail_description', models.TextField(help_text='Подробное описание доски, видно которое пользователи видят в шапке самой доски', null=True)),
                ('banner', models.FileField(default=None, help_text='Приветственный баннер', null=True, upload_to='')),
                ('thread_limit', models.IntegerField(default=1000, help_text='Количество тредов, при котором старые начнут удаляться, давая место новым (0 для неограниченного количества)')),
                ('bump_limit', models.IntegerField(default=500, help_text="Бамплимит. При достижении (бамплимит) комментариев в треде он 'утонет' (удалится) (0 для выключения бамплимита)")),
                ('is_nsfw', models.BooleanField(default=False, help_text='Помечает борд как NSFW. Файлы с тредов в NSFW бордах отправляются МКБотом под спойлером, а сама категория помечается красным цветом.')),
                ('enable_posting', models.BooleanField(default=True, help_text='Если False, разрешает постинг в борде только админам (борда всё ещё будет доступна для просмотра из списка)')),
                ('lockdown', models.BooleanField(default=False, help_text='Карантин. В карантинных бордах НЕЛЬЗЯ создавать или бампать треды.')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название Категории')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('author_code', models.TextField(default=None, help_text='Код автора, задаётся автоматически.', null=True)),
                ('is_nsfw', models.BooleanField(default=False, help_text='Является ли коммент NSFW (всегда True для комментов под NSFW тредами)')),
                ('text', models.TextField(help_text='Текст')),
                ('author', models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.anon')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Код разрешения.')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('title', models.CharField(default='None', help_text='Заголовок', max_length=64)),
                ('text', models.TextField(help_text='Текст')),
                ('rating', models.IntegerField(default=0, help_text='Рейтинг треда. Он задаётся автоматически, крайне не рекомендуется менять вручную!!!')),
                ('is_nsfw', models.BooleanField(default=False, help_text='Является ли тред NSFW (всегда True для комментов на NSFW бордах)')),
                ('pinned', models.BooleanField(default=False, help_text='Если тред закреплён, он будет отображаться в самом начале списка тредов. Также можно задать из контектного меню треда если вы админ.')),
                ('author', models.ForeignKey(help_text='Создатель треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.anon')),
                ('board', models.ForeignKey(help_text='Доска треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.board')),
            ],
            options={
                'permissions': [('create_new_threads', 'Can create new threads'), ('comment_threads', 'Can comment threads')],
            },
        ),
        migrations.CreateModel(
            name='ThreadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif'])])),
                ('thread', models.ForeignKey(help_text='Тред, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'mp4', 'webm', 'gif'])])),
                ('comment', models.ForeignKey(help_text='Коммент, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(help_text='Тред, к которому пишется комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread'),
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.category'),
        ),
        migrations.AddField(
            model_name='board',
            name='permissions_required',
            field=models.ManyToManyField(blank=True, to='boards.permission'),
        ),
        migrations.AddField(
            model_name='anon',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='boards.permission'),
        ),
    ]
